CREATE TABLE IF NOT EXISTS "user" (
    "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "password" VARCHAR(255) NOT NULL,
    "full_name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP(6) NOT NULL,
    "updated_at" TIMESTAMP(6) NOT NULL,
    "token_version" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "template" (
    "template_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "template_name" VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS "cv" (
    "cv_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "template_id" BIGINT NOT NULL,
    "title" VARCHAR(255),
    "summary" TEXT,
    "created_at" TIMESTAMP(6),
    "updated_at" TIMESTAMP(6),
    CONSTRAINT "fk_cv_user" FOREIGN KEY ("user_id") REFERENCES "user" ("user_id"),
    CONSTRAINT "fk_cv_template" FOREIGN KEY ("template_id") REFERENCES "template" ("template_id")
);

CREATE TABLE IF NOT EXISTS "personal_information" (
    "info_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cv_id" BIGINT UNIQUE,
    "full_name" VARCHAR(255) NOT NULL,
    "job_title" VARCHAR(255) NOT NULL,
    "contact_email" VARCHAR(255) NOT NULL,
    "phone" VARCHAR(255),
    "location" VARCHAR(255),
    "linked_in" VARCHAR(255),
    "website" VARCHAR(255),
    CONSTRAINT "fk_personal_information_cv" FOREIGN KEY ("cv_id") REFERENCES "cv" ("cv_id")
);

CREATE TABLE IF NOT EXISTS "education" (
    "education_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cv_id" BIGINT,
    "school" VARCHAR(255) NOT NULL,
    "degree" VARCHAR(255) NOT NULL,
    "start_date" TIMESTAMP(6),
    "end_date" TIMESTAMP(6),
    "description" TEXT,
    CONSTRAINT "fk_education_cv" FOREIGN KEY ("cv_id") REFERENCES "cv" ("cv_id")
);

CREATE TABLE IF NOT EXISTS "experience" (
    "experience_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cv_id" BIGINT,
    "company" VARCHAR(255) NOT NULL,
    "job_title" VARCHAR(255),
    "start_date" VARCHAR(255),
    "end_date" VARCHAR(255),
    "description" TEXT,
    CONSTRAINT "fk_experience_cv" FOREIGN KEY ("cv_id") REFERENCES "cv" ("cv_id")
);

CREATE TABLE IF NOT EXISTS "project" (
    "project_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cv_id" BIGINT,
    "project_name" VARCHAR(255) NOT NULL,
    "role" VARCHAR(255),
    "link" VARCHAR(255),
    "description" TEXT,
    CONSTRAINT "fk_project_cv" FOREIGN KEY ("cv_id") REFERENCES "cv" ("cv_id")
);

CREATE TABLE IF NOT EXISTS "certificate" (
    "certificate_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cv_id" BIGINT,
    "certificate_name" VARCHAR(255) NOT NULL,
    "organization" VARCHAR(255),
    "issue_date" TIMESTAMP(6),
    CONSTRAINT "fk_certificate_cv" FOREIGN KEY ("cv_id") REFERENCES "cv" ("cv_id")
);

CREATE TABLE IF NOT EXISTS "skill" (
    "skill_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cv_id" BIGINT,
    "skill_name" VARCHAR(255) NOT NULL,
    CONSTRAINT "fk_skill_cv" FOREIGN KEY ("cv_id") REFERENCES "cv" ("cv_id")
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'user'
          AND column_name = 'token_version'
    ) THEN
        ALTER TABLE "user" ADD COLUMN "token_version" INTEGER NOT NULL DEFAULT 0;
    END IF;
END $$;

ALTER TABLE "cv" ALTER COLUMN "summary" TYPE TEXT;
ALTER TABLE "education" ALTER COLUMN "description" TYPE TEXT;
ALTER TABLE "experience" ALTER COLUMN "description" TYPE TEXT;
ALTER TABLE "project" ALTER COLUMN "description" TYPE TEXT;

INSERT INTO "template" ("template_id", "template_name") VALUES
    (1, 'Modern'),
    (2, 'Minimal'),
    (3, 'Classic'),
    (4, 'Creative'),
    (5, 'Professional'),
    (6, 'Elegant'),
    (7, 'Classic 2'),
    (8, 'Professional 2'),
    (9, 'Modern 2')
ON CONFLICT ("template_id") DO UPDATE
SET "template_name" = EXCLUDED."template_name";

SELECT setval(pg_get_serial_sequence('"template"', 'template_id'), (SELECT MAX("template_id") FROM "template"));
